version: '3'
services:
  php:
    build:
      context: ./docker/php/
    volumes:
      - './app:/var/www/html'

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - './app:/var/www/html'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'

  mysql:
    image: mysql:8
    environment:
      - MYSQL_DATABASE=mysql
      - MYSQL_USER=user
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - './docker/volumes/mysql:/var/lib/mysql/'
    ports:
      - 3306:3306
